FROM node:argon

RUN npm install -g bower grunt-cli

RUN mkdir /app
WORKDIR /app

COPY package.json .
RUN npm install

COPY bower.json .
COPY .bowerrc .
RUN bower install

COPY . .

RUN grunt

EXPOSE 3000
CMD [ "npm", "start" ]
