nginx:
  image: nginx:1.10
  container_name: nginx
  ports:
    - '8080:80'
  links:
    - app
  volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  command: nginx -g 'daemon off;'

mongo:
  image: mongo:3
  container_name: mongo
  volumes:
    - /var/lib/docker/volumes/mongo/data:/data/db

app:
  build: .
  container_name: app
  command: nodemon -L server.js
  links:
    - mongo
  ports:
    - '3000:3000'
  volumes:
    - .:/app
  env_file:
    - .env
