mongo:
  image: mongo:3
  container_name: mongo
  volumes:
    - /var/lib/docker/volumes/mongo/data:/data/db

app:
  build: .
  container_name: app
  command: npm start
  links:
    - mongo
  ports:
    - '3000:3000'
  volumes:
    - .:/app
  env_file:
    - .env
