---
- hosts: loadbalancer
  become: true
  tasks:
    - name: stop nginx
      service: name=nginx state=stopped

    - wait_for: port=80 state=stopped

- hosts: webserver
  become: true
  tasks:
    - name: stop node app
      service: name=notes state=stopped

    - wait_for: port=3000 state=stopped

- hosts: database
  become: true
  tasks:
    - name: restart mongo
      service: name=mongo state=restarted

- hosts: webserver
  become: true
  tasks:
    - name: restart node app
      service: name=notes state=restarted

    - wait_for: port=3000 state=started  

- hosts: loadbalancer
  become: true
  tasks:
    - name: restart nginx
      service: name=nginx state=restarted

    - wait_for: port=80 state=started
