---
- name: checkout app repo
  git: repo={{ app_repo_url }} dest={{ app_source_folder }}
  notify: restart notes

- name: build app image
  docker_image:
    path: "{{ app_source_folder }}"
    state: present
    name: "{{ app_container_name }}"
    tag: latest
  notify: restart notes

- name: ensure notes is started
  service: name=notes state=started
