#! /usr/bin/env bash

REPO_NAME="notes"
export GIT_WORK_TREE="/var/git/${REPO_NAME}"
git checkout -f

FULL_LATEST_TAG="${REPO_NAME}:latest"

docker build -t "${FULL_LATEST_TAG}" "${GIT_WORK_TREE}"

echo "Restarting ${REPO_NAME}"
docker stop "${REPO_NAME}"
