---
- name: pull node image
  docker_image:
    name: node
    state: present
    tag: 'argon'

- name: copy .env file
  copy: src=.env dest={{ work_tree_folder }}

- name: copy upstart script
  copy: src=notes.conf dest=/etc/init

- name: ensure notes is started
  service: name=notes state=started
