---
- name: pull node image
  docker_image:
    name: node
    state: present
    tag: 'argon'

- name: copy .env file
  template: src=.notes.env.j2 dest={{ work_tree_folder }}/.notes.env

- name: copy upstart script
  copy: src=notes.conf dest=/etc/init

- name: ensure notes is started
  service: name=notes state=started
