---
- name: ensure git is installed
  apt: name=git state=present

- name: create git repo folder
  file: path={{ repo_folder }} state=directory

- name: create bare repo
  action: command chdir={{ repo_folder }} creates={{ repo_folder }}/HEAD git init --bare warn=no
  changed_when: false


- name: give permission to ssh user in repo folder
  file: path={{ repo_folder }} owner={{ ssh_user }} group={{ ssh_user }} state=directory recurse=yes
  changed_when: false

- name: git work tree folder
  file: path={{ work_tree_folder }} owner={{ ssh_user }} group={{ ssh_user }} state=directory recurse=yes

- name: deploy script as post receive git hook
  copy: src=post-receive dest={{ repo_folder }}/hooks owner={{ ssh_user }} group={{ ssh_user }} mode=755
