---
- hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: install packages
      apt: name={{ item }} state=present
      with_items:
        - htop

  roles:
    - docker
    - user
