---
- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=86400
  roles:
    - docker
    - user

- include: loadbalancer.yml
- include: database.yml
- include: webserver.yml
