Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "staging"
  config.vm.network "private_network", ip: "192.168.99.120"

  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  config.vm.provision "file", source: '~/.ssh/id_rsa.pub', destination: '~/key.pub'
  config.vm.provision :shell, inline: 'cat /home/vagrant/key.pub >> /home/vagrant/.ssh/authorized_keys'
end
