---
- hosts: webserver
  become: true
  gather_facts: false
  roles:
    - git-repo
    
  tasks:
    - name: pull node image
      docker_image:
        name: node:argon
        state: present
      changed_when: false
